# Generated by Django 5.0.6 on 2024-07-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="longperiodtasks",
            name="ischecked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasks",
            name="ischecked",
            field=models.BooleanField(default=False),
        ),
    ]
