# Generated by Django 5.0.6 on 2024-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Info", "0002_longperiodtasks_ischecked_tasks_ischecked"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
