# Generated by Django 5.0.6 on 2024-07-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Info", "0003_tasks_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="index",
        ),
    ]
