# Generated by Django 5.0.6 on 2024-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Info", "0004_remove_tasks_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="famoussentencestasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentences", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
            ],
        ),
    ]
